### ISSUE TITLE
Override queued hooks if ULX is installed

### ISSUE THREAD

**Issue by Kefta** [SuperiorServers/plib_v2#46]
ULX currently does a numeric loop to go through its priorities every hook.Call. This can be done way better by making a priority queue and putting the load on hook.Add.

**Comment by aStonedPenguin** [comment]
We're not adding comparability for cancer. plib is to be used as a sole development platform, not an addon you can paste into your cancer server.

**Comment by thelastpenguin** [comment]
@Kefta I just want to add on here that the initial design of the hook system in plib means that hooks will get called in the order that they are added. This means that priority is implemented through load order the way it really should be rather than autism (aka priority classes).

With a proper plugin and dependency loading system hooks will just work themselves out automagically.

**Comment by Kefta** [comment]
@thelastpenguin My plan wasn't to change how pLib's hooks work inherently, but only change how the system works if ULX is installed, since our version is currently overwritten when ULX loads. I'm just going to submit my version to ULX proper to benefit every one.
